# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sf/v2/geometry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sf/v2/geometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sf/v2/geometry.proto\x12\x05sf.v2\"\"\n\x03\x43rs\x12\x0c\n\x04srid\x18\x01 \x01(\r\x12\r\n\x05scale\x18\x02 \x01(\r\"\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x11\x12\t\n\x01y\x18\x02 \x01(\x11\")\n\x05Point\x12 \n\x05\x63oord\x18\x01 \x01(\x0b\x32\x11.sf.v2.Coordinate\"*\n\nMultiPoint\x12\x1c\n\x06points\x18\x01 \x03(\x0b\x32\x0c.sf.v2.Point\"K\n\x0f\x44\x65ltaLineString\x12 \n\x05start\x18\x01 \x01(\x0b\x32\x11.sf.v2.Coordinate\x12\n\n\x02\x64x\x18\x02 \x03(\x11\x12\n\n\x02\x64y\x18\x03 \x03(\x11\"E\n\tDeltaRing\x12 \n\x05start\x18\x01 \x01(\x0b\x32\x11.sf.v2.Coordinate\x12\n\n\x02\x64x\x18\x02 \x03(\x11\x12\n\n\x02\x64y\x18\x03 \x03(\x11\"*\n\x07Polygon\x12\x1f\n\x05rings\x18\x01 \x03(\x0b\x32\x10.sf.v2.DeltaRing\"?\n\x0fMultiLineString\x12,\n\x0cline_strings\x18\x01 \x03(\x0b\x32\x16.sf.v2.DeltaLineString\"0\n\x0cMultiPolygon\x12 \n\x08polygons\x18\x01 \x03(\x0b\x32\x0e.sf.v2.Polygon\"\xa5\x02\n\x08Geometry\x12\x17\n\x03\x63rs\x18\x01 \x01(\x0b\x32\n.sf.v2.Crs\x12\x1d\n\x05point\x18\n \x01(\x0b\x32\x0c.sf.v2.PointH\x00\x12-\n\x0bline_string\x18\x0b \x01(\x0b\x32\x16.sf.v2.DeltaLineStringH\x00\x12!\n\x07polygon\x18\x0c \x01(\x0b\x32\x0e.sf.v2.PolygonH\x00\x12+\n\x0cmultipolygon\x18\r \x01(\x0b\x32\x13.sf.v2.MultiPolygonH\x00\x12\x31\n\x0fmultilinestring\x18\x0e \x01(\x0b\x32\x16.sf.v2.MultiLineStringH\x00\x12\'\n\nmultipoint\x18\x0f \x01(\x0b\x32\x11.sf.v2.MultiPointH\x00\x42\x06\n\x04geomb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sf.v2.geometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CRS']._serialized_start=31
  _globals['_CRS']._serialized_end=65
  _globals['_COORDINATE']._serialized_start=67
  _globals['_COORDINATE']._serialized_end=101
  _globals['_POINT']._serialized_start=103
  _globals['_POINT']._serialized_end=144
  _globals['_MULTIPOINT']._serialized_start=146
  _globals['_MULTIPOINT']._serialized_end=188
  _globals['_DELTALINESTRING']._serialized_start=190
  _globals['_DELTALINESTRING']._serialized_end=265
  _globals['_DELTARING']._serialized_start=267
  _globals['_DELTARING']._serialized_end=336
  _globals['_POLYGON']._serialized_start=338
  _globals['_POLYGON']._serialized_end=380
  _globals['_MULTILINESTRING']._serialized_start=382
  _globals['_MULTILINESTRING']._serialized_end=445
  _globals['_MULTIPOLYGON']._serialized_start=447
  _globals['_MULTIPOLYGON']._serialized_end=495
  _globals['_GEOMETRY']._serialized_start=498
  _globals['_GEOMETRY']._serialized_end=791
# @@protoc_insertion_point(module_scope)
