# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sf/v1/geometry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sf/v1/geometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sf/v1/geometry.proto\x12\x05sf.v1\"\x13\n\x03\x43rs\x12\x0c\n\x04srid\x18\x01 \x01(\r\"\"\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\")\n\x05Point\x12 \n\x05\x63oord\x18\x01 \x01(\x0b\x32\x11.sf.v1.Coordinate\"*\n\nMultiPoint\x12\x1c\n\x06points\x18\x01 \x03(\x0b\x32\x0c.sf.v1.Point\"*\n\nLineString\x12\x1c\n\x06points\x18\x01 \x03(\x0b\x32\x0c.sf.v1.Point\":\n\x0fMultiLineString\x12\'\n\x0cline_strings\x18\x01 \x03(\x0b\x32\x11.sf.v1.LineString\"/\n\nLinearRing\x12!\n\x06\x63oords\x18\x01 \x03(\x0b\x32\x11.sf.v1.Coordinate\"+\n\x07Polygon\x12 \n\x05rings\x18\x01 \x03(\x0b\x32\x11.sf.v1.LinearRing\"0\n\x0cMultiPolygon\x12 \n\x08polygons\x18\x01 \x03(\x0b\x32\x0e.sf.v1.Polygon\"\xa0\x02\n\x08Geometry\x12\x17\n\x03\x63rs\x18\x01 \x01(\x0b\x32\n.sf.v1.Crs\x12\x1d\n\x05point\x18\n \x01(\x0b\x32\x0c.sf.v1.PointH\x00\x12(\n\x0bline_string\x18\x0b \x01(\x0b\x32\x11.sf.v1.LineStringH\x00\x12!\n\x07polygon\x18\x0c \x01(\x0b\x32\x0e.sf.v1.PolygonH\x00\x12+\n\x0cmultipolygon\x18\r \x01(\x0b\x32\x13.sf.v1.MultiPolygonH\x00\x12\x31\n\x0fmultilinestring\x18\x0e \x01(\x0b\x32\x16.sf.v1.MultiLineStringH\x00\x12\'\n\nmultipoint\x18\x0f \x01(\x0b\x32\x11.sf.v1.MultiPointH\x00\x42\x06\n\x04geomb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sf.v1.geometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CRS']._serialized_start=31
  _globals['_CRS']._serialized_end=50
  _globals['_COORDINATE']._serialized_start=52
  _globals['_COORDINATE']._serialized_end=86
  _globals['_POINT']._serialized_start=88
  _globals['_POINT']._serialized_end=129
  _globals['_MULTIPOINT']._serialized_start=131
  _globals['_MULTIPOINT']._serialized_end=173
  _globals['_LINESTRING']._serialized_start=175
  _globals['_LINESTRING']._serialized_end=217
  _globals['_MULTILINESTRING']._serialized_start=219
  _globals['_MULTILINESTRING']._serialized_end=277
  _globals['_LINEARRING']._serialized_start=279
  _globals['_LINEARRING']._serialized_end=326
  _globals['_POLYGON']._serialized_start=328
  _globals['_POLYGON']._serialized_end=371
  _globals['_MULTIPOLYGON']._serialized_start=373
  _globals['_MULTIPOLYGON']._serialized_end=421
  _globals['_GEOMETRY']._serialized_start=424
  _globals['_GEOMETRY']._serialized_end=712
# @@protoc_insertion_point(module_scope)
