# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sf/v7/geometry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sf/v7/geometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sf/v7/geometry.proto\x12\x05sf.v7\x1a\x1cgoogle/protobuf/struct.proto\"\"\n\x03\x43rs\x12\x0c\n\x04srid\x18\x01 \x01(\r\x12\r\n\x05scale\x18\x02 \x01(\r\"#\n\x0b\x43oordinateQ\x12\t\n\x01x\x18\x01 \x01(\x11\x12\t\n\x01y\x18\x02 \x01(\x11\"j\n\x0eStreamGeometry\x12\x1d\n\x04type\x18\x01 \x01(\x0e\x32\x0f.sf.v7.GeomType\x12\x0b\n\x03\x64xy\x18\x02 \x03(\x11\x12\x12\n\npart_sizes\x18\x03 \x03(\r\x12\x18\n\x10poly_ring_counts\x18\x04 \x03(\r\"\xa1\x01\n\x07\x46\x65\x61ture\x12\'\n\x08geometry\x18\x01 \x01(\x0b\x32\x15.sf.v7.StreamGeometry\x12+\n\nproperties\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\n\n\x02id\x18\x03 \x01(\t\x12\x0c\n\x04\x62\x62ox\x18\x04 \x03(\x01\x12&\n\x05\x65xtra\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\"\xbc\x01\n\x11\x46\x65\x61tureCollection\x12 \n\x08\x66\x65\x61tures\x18\x01 \x03(\x0b\x32\x0e.sf.v7.Feature\x12\x0c\n\x04\x62\x62ox\x18\x02 \x03(\x01\x12&\n\x05\x65xtra\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x17\n\x03\x63rs\x18\x05 \x01(\x0b\x32\n.sf.v7.Crs\x12(\n\x0cglobal_start\x18\x06 \x01(\x0b\x32\x12.sf.v7.CoordinateQ\"\xb8\x01\n\x12GeometryCollection\x12)\n\ngeometries\x18\x01 \x03(\x0b\x32\x15.sf.v7.StreamGeometry\x12\x0c\n\x04\x62\x62ox\x18\x02 \x03(\x01\x12&\n\x05\x65xtra\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x17\n\x03\x63rs\x18\x04 \x01(\x0b\x32\n.sf.v7.Crs\x12(\n\x0cglobal_start\x18\x05 \x01(\x0b\x32\x12.sf.v7.CoordinateQ*\x7f\n\x08GeomType\x12\x14\n\x10GEOM_UNSPECIFIED\x10\x00\x12\t\n\x05POINT\x10\x01\x12\x0e\n\nMULTIPOINT\x10\x02\x12\x0e\n\nLINESTRING\x10\x03\x12\x13\n\x0fMULTILINESTRING\x10\x04\x12\x0b\n\x07POLYGON\x10\x05\x12\x10\n\x0cMULTIPOLYGON\x10\x06\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sf.v7.geometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GEOMTYPE']._serialized_start=784
  _globals['_GEOMTYPE']._serialized_end=911
  _globals['_CRS']._serialized_start=61
  _globals['_CRS']._serialized_end=95
  _globals['_COORDINATEQ']._serialized_start=97
  _globals['_COORDINATEQ']._serialized_end=132
  _globals['_STREAMGEOMETRY']._serialized_start=134
  _globals['_STREAMGEOMETRY']._serialized_end=240
  _globals['_FEATURE']._serialized_start=243
  _globals['_FEATURE']._serialized_end=404
  _globals['_FEATURECOLLECTION']._serialized_start=407
  _globals['_FEATURECOLLECTION']._serialized_end=595
  _globals['_GEOMETRYCOLLECTION']._serialized_start=598
  _globals['_GEOMETRYCOLLECTION']._serialized_end=782
# @@protoc_insertion_point(module_scope)
